# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

id: ig-eTwoDocs
canonical: http://jpfhir.jp/fhir/jp-eTwoDocs
name: "2文書（診療情報提供書・退院時サマリー）のFHIR実装ガイド  v1.0.0-rc1 リリース候補v1"
title: "2文書（診療情報提供書・退院時サマリー）のFHIR実装ガイド  v1.0.0-rc1 リリース候補v1"
description: "2文書（診療情報提供書・退院時サマリー）のFHIR実装ガイド  v1.0.0-rc1 リリース候補v1"
status: draft # draft | active | retired | unknown 
version: 1.0.0-rc1
date: 2024-06-24
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html 
copyrightYear: 2023+
releaseLabel: draft # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC BY-ND  #  https://www.hl7.org/fhir/valueset-spdx-license.html
# https://www.hl7.org/fhir/valueset-jurisdiction.html 
publisher:
  name: 管理：（一社）日本医療情報学会.
  url: https://jami.jp
  email: office@jami.jp
copyright: （一社）日本医療情報学会. CC BY-ND 4.0 （クリエイティブ・コモンズ 表示-改変禁止 4.0 国際 パブリック・ライセンス）
jurisdiction: 'urn:iso:std:iso:3166-2#JP'
dependencies:
  jp-core.r4:
    uri: http://jpfhir.jp/fhir/core/1.1.2/ImplementationGuide/
    version: 1.1.2
  jpfhir-terminology.r4:
    uri: http://jpfhir.jp/fhir//jpfhir-terminology.r4/ImplementationGuide/
    version: 1.1.1
#----------------------------------------
# ページタイトル名称設定
#----------------------------------------
pages:
  index.md:
    title: 2文書（診療情報提供書・退院時サマリー）のFHIR実装ガイド  JP-eTwoDocs
  history.md:
    title: 変更履歴
  validationGuide.md:
    title: Validationガイド
    
#-------------------------------------
# メニュー設定
#-------------------------------------
menu:
  Home:
    本文: index.html
    変更履歴: history.html
    プロファイル: artifacts.html
  Artifacts: 
    Artifacts: artifacts.html
  Validationガイド:
    Validationガイド: validationGuide.html    
  パッケージDownload:
    標準(diff)版: https://jpfhir.jp/fhir/eTwoDocs/jp-eTwoDocs.r4-1.0.0.tgz
    snapshot版: https://jpfhir.jp/fhir/eTwoDocs/jp-eTwoDocs.r4-1.0.0-snap.tgz    
#-----------------------------------------
# IG 外部パラメータ設定
#-----------------------------------------
parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
  path-pages:
    - input/pagecontent
    - input/intro-notes
    - fsh-generated/includes
    #- input/summaries
  path-expansion-params: '../../input/_resources/exp-params.json'
  no-narrative: 
    - CodeSystem/*
  active-tables: 'false'
  apply-version: 'true'
  apply-copyright: 'true'
  apply-publisher: 'true'
  apply-contact: 'true'
  apply-license: 'true'
  apply-jurisdiction: 'true'
  show-inherited-invariants: 'true'
  usage-stats-opt-out: 'true'
  display-warnings: 'true'
  excludexml: 'true'
  excludejson: 'false'
  excludettl: 'true'
  excludemap: 'true'
#  excludeexample: 'false'
  generate: #what does this do - todo: remove and see
    - json
  no-validate:
    - '*/hl7.fhir.jp.core'
  special-url:
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_AllergyIntolerance_eCS
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_Binary
    - http://jpfhir.jp/fhir/eDischargeSummary/StructureDefinition/JP_Bundle_eDischargeSummary
    - http://jpfhir.jp/fhir/clins/StructureDefinition/JP_Bundle_eReferral
    - http://jpfhir.jp/fhir/StructureDefinition/JP_Bundle
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_CarePlan_eCS
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_CarePlan
    - http://jpfhir.jp/fhir/eDischargeSummary/StructureDefinition/JP_Composition_eDischargeSummary
    - http://jpfhir.jp/fhir/eReferral/StructureDefinition/JP_Composition_eReferral
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Condition_eCS
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Consent_eCS
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_Consent
    - http://jpfhir.jp/fhir/ePrescription/StructureDefinition/JP_Coverage_eCS_insurance
    - http://jpfhir.jp/fhir/ePrescription/StructureDefinition/JP_Coverage_eCS_publicPayment
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Device_eCS
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_Device
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_DeviceUseStatement_eCS
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_DeviceUseStatement
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_DocumentReference_CDAdocument
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_DocumentReference_eCS
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_DocumentReference
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Encounter_eCS
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_FamilyMemberHistory_eCS
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Immunization_eCS
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_Immunization
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_MedicationRequest_eCS
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Observation_LabResult_eCS
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Observation_Common_eCS
    - http://jpfhir.jp/fhir/ePrescription/StructureDefinition/JP_Organization_eCS_coveragePayer
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Organization_eCS_department
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Organization_eCS
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Patient_eCS
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Practitioner_eCS
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Practitioner_eCS_author
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_PractitionerRole_eCS_author
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Procedure_eCS
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_RelatedPerson_eCS
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_RelatedPerson
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_ResearchStudy_eCS
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_ResearchStudy
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_ResearchSubject_eCS
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_ResearchSubject
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_ServiceRequest
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_Specimen
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_MedicationDosage_eCS
    - http://jpfhir.jp/fhir/eDischargeSummary/Extension/StructureDefinition/JP_Communication_CommunicationContent
    - http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Condition_DiseasePostfixModifier
    - http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Condition_DiseasePrefixModifier
    - http://jpfhir.jp/fhir/eCS/Extension/StructureDefinition/JP_eCS_Department
    - http://jpfhir.jp/fhir/eCS/Extension/StructureDefinition/JP_eCS_DiagnosisType
    - http://jpfhir.jp/fhir/clins/Extension/StructureDefinition/JP_eCS_InstitutionNumber
    - http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationRequest_DispenseRequest_InstructionForDispense
    - http://jpfhir.jp/fhir/Common/CodeSystem/admit-Source
    - http://jpfhir.jp/fhir/CarePlan/CodeSystem/category
    - http://jpfhir.jp/fhir/clins/CodeSystem/BundleResourceType_CS
    - http://jpfhir.jp/fhir/clins/CodeSystem/JP_CLINS_ObsLabResult_CoreLabo_CS
    - http://jpfhir.jp/fhir/clins/CodeSystem/JP_CLINS_ObsLabResult_InfectionLabo_CS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_ObservationLabResultLocalUncoded_CS
    - http://jpfhir.jp/fhir/clins/CodeSystem/JP_CLINS_ObsLabResult_Uncoded_CS
    - http://jpfhir.jp/fhir/Common/CodeSystem/discharge-disposition
    - http://jpfhir.jp/fhir/Common/CodeSystem/doc-typecodes
    - http://loinc.org
    - http://jpfhir.jp/fhir/eDischargeSummary/CodeSystem/document-section
    - http://jpfhir.jp/fhir/eReferral/CodeSystem/document-section
    - http://jpfhir.jp/fhir/eCS/CodeSystem/MedicationCodeNocoded_CS
    - http://jpfhir.jp/fhir/clins/CodeSystem/JP_ehrshrs_indication
    - http://jpfhir.jp/fhir/eCS/CodeSystem/observation-subcategory-cs
    - http://jpfhir.jp/fhir/core/CodeSystem/JP_SimpleObservationCategory_CS
    - http://jpfhir.jp/fhir/CarePlan/ValueSet/category
    - http://jpfhir.jp/fhir/Common/ValueSet/admit-Source
    - http://jpfhir.jp/fhir/clins/ValueSet/BundleResourceType_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_abo_bld_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_alb_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_alp_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_alt_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_amy_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_aptt_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_ast_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_bnp_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_bs_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_bun_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_ca_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_che_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_ck_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_cl_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_cre_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_crp_class_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_crp_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_cys_c_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_d_bil_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_dd_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_fbs_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_ggt_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_hb_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_hba1c_ngsp_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_hdl_c_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_plt_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_k_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_ld_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_ldl_c_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_na_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_nt_probnp_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_pt_act_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_pt_inr_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_pt_ratio_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_pt_sec_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_rbc_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_rh_bld_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_t_bil_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_t_cho_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_tg_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_tp_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_u_ac_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_u_bld_HalfQty_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_u_bld_QLHalfQty_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_u_bld_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_u_glu_HalfQty_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_u_glu_QLHalfQty_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_u_glu_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_u_pc_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_ua_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_utp_HalfQty_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_utp_QLHalfQty_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_utp_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_CoreLabo_wbc_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HBsABCOI_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HBsABDIL_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HBsABNEGCOI_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HBsABQUANT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HBsABRESULT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HBsAGCOI_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HBsAGDIL_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HbsAGOD_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HBsAGPOSCOI_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HBsAGQUANT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HBsAGRESULT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HBSAGSCO_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HCVABCOI_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HCVABDIL_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HCVABPOSCOI_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HCVABRESULT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HCVAGQUANT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HCVAGRESULT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HCVCHECK_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HCVQUANT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HCVRESULT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1ABDIL_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1ABRESULT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1P2ABCOI_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1P2ABDIL_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1P2ABOD_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1P2ABP24COI_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1P2ABPOSCOIV_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1P2ABP24NEGCOI_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1P2ABP24POSCOI_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1P2ABP24QLRESULT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1P2ABP24RESULT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1P2ABPOSCOI_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1P2ABQUANT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1P2ABRESULT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1P2P24ABQUANT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1P2P24ABRESULT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1QUANT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV1RESULT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV2ABDIL_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_HIV2ABRESULT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_STS_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_STSHQUANT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_STSQLRESULT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_STSQUANT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_STSRESULT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_TPHQUANT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_TPNEGCOI_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_TPPOSCOI_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_TPQUANT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_TPQUANTCOI_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_TPQUANTRESULT_VS
    - http://jpfhir.jp/fhir/clins/ValueSet/JP_CLINS_ObsLabResult_InfectionLabo_TPRESULT_VS
    - http://jpfhir.jp/fhir/eDischargeSummary/ValueSet/document-section
    - http://jpfhir.jp/fhir/Common/ValueSet/discharge-disposition
    - http://jpfhir.jp/fhir/eCS/CodeSystem/MedicationCodeNocoded_VS
    - http://jpfhir.jp/fhir/eCS/ValueSet/JP_eCS_ObservationLabResultCode_VS
    - http://jpfhir.jp/fhir/Common/ValueSet/doc-typecodes
    - http://jpfhir.jp/fhir/eReferral/ValueSet/document-section

